
#' Quantitative Variable Distribution -- Output Generation
#'
#' Using the tabular output generated by `qvd_process`, this function will build a graph to
#' visualize the results. Each function configuration will output a bespoke ggplot. Theming can
#' be adjusted by the user after the graph has been output using `+ theme()`. Most graphs can
#' also be made interactive using `make_interactive_squba()`
#'
#' @param process_output *tabular output* | the output of the `qvd_process` function
#' @param value_type_filter *string / vector* | a string or vector of strings to filter the graph to specific variables of interest
#' @param frequency_min *integer* | an integer to establish a minimum amount of times a value should occur to be included in the output;
#'                      aimed at trimming infrequently occurring outliers for a cleaner plot; defaults to 5
#' @param display_outliers *boolean* | for boxplot output, a boolean to indicate whether outliers should be displayed; defaults to FALSE
#' @param summary_stat *string* | a string indicating the summary statistic that should be displayed on the plot; required for
#'                     exploratory, longitudinal results; defaults to `mean`, but `median`, `q1`, `q3`, or `sd` are also accepted
#' @param large_n *boolean* | for multi site analyses, a boolean indicating whether the large N visualization, intended for a high
#'                volume of sites, should be used; defaults to FALSE
#' @param large_n_sites *vector* | when large_n is TRUE, a vector of site names that can optionally generate a filtered visualization
#'
#' @returns a graph to visualize the results from `qvd_process` based on the parameters provided; see documentation
#'          for individual subfunctions for details on specific output
#' @export
#'
#' @import ggplot2
#' @import ggiraph
#' @import gt
#' @import patchwork
#' @importFrom grDevices colorRampPalette
#' @importFrom ggdist stat_halfeye
#' @importFrom stringr str_to_sentence
#'
qvd_output <- function(process_output,
                       value_type_filter = NULL,
                       frequency_min = 5,
                       display_outliers = FALSE,
                       summary_stat = 'mean',
                       large_n = FALSE,
                       large_n_sites = NULL){

  output_string <- process_output %>% ungroup() %>%
    distinct(output_function) %>% pull()

  if(output_string == 'qvd_ss_exp_cs'){
    qvd_plt <- qvd_ss_exp_cs(process_output = process_output,
                             display_outliers = display_outliers,
                             frequency_min = frequency_min,
                             value_type_filter = value_type_filter)
  }else if(output_string == 'qvd_ms_exp_cs'){
    qvd_plt <- qvd_ms_exp_cs(process_output = process_output,
                             display_outliers = display_outliers,
                             frequency_min = frequency_min,
                             value_type_filter = value_type_filter,
                             large_n = large_n,
                             large_n_sites = large_n_sites)
  }else if(output_string == 'qvd_ss_anom_cs'){
    qvd_plt <- qvd_ss_anom_cs(process_output = process_output)
  }else if(output_string == 'qvd_ms_anom_cs'){
    qvd_plt <- qvd_ms_anom_cs(process_output = process_output,
                              value_type_filter = value_type_filter,
                              large_n = large_n,
                              large_n_sites = large_n_sites)
  }else if(output_string == 'qvd_ss_exp_la'){
    qvd_plt <- qvd_ss_exp_la(process_output = process_output,
                             value_type_filter = value_type_filter,
                             summary_stat = summary_stat)
  }else if(output_string == 'qvd_ms_exp_la'){
    qvd_plt <- qvd_ms_exp_la(process_output = process_output,
                             value_type_filter = value_type_filter,
                             summary_stat = summary_stat,
                             large_n = large_n,
                             large_n_sites = large_n_sites)
  }else if(output_string == 'qvd_ss_anom_la'){
    qvd_plt <- qvd_ss_anom_la(process_output = process_output,
                              value_type_filter = value_type_filter)
  }else if(output_string == 'qvd_ms_anom_la'){
    qvd_plt <- qvd_ms_anom_la(process_output = process_output,
                              value_type_filter = value_type_filter,
                              large_n = large_n,
                              large_n_sites = large_n_sites)
  }

  return(qvd_plt)

}
